options:
  size: 2x

definitions:
  services:
    docker:
      memory: 4096


pipelines:
  custom:
    build-and-deploy-evmx-staging:
      - step:
          image: python:3.9-alpine
          name: Build Image
          services:
            - docker
          caches:
            - pip
            - docker
          script:
            - pip3 install awscli
            - eval $(aws ecr get-login --no-include-email --region "${AWS_REGION}" | sed 's;https://;;g')
            - docker build -t  $IMAGE --build-arg BASE_GRAPHQL_SERVER_URL=$STAGINIG_BASE_GRAPHQL_SERVER_URL --build-arg AMCHARTS_LICENSE=$AMCHARTS_LICENSE .
            - docker push $IMAGE_NAME
